[package]
name = "kanaria_extern"
version = "0.1.0"
authors = ["osamu <46447427+sam-osamu@users.noreply.github.com>"]
edition = "2018"

[dependencies]
kanaria = { path = "../core" }

[lib]
name = "kanaria_core"
path = "src/lib.rs"
crate-type = ["dylib"]